# Generated by Django 4.1.3 on 2022-12-06 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lojacarford", "0006_alter_carro_proprietario"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Carro",
        ),
    ]
