# Generated by Django 4.1.3 on 2022-12-06 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lojacarford", "0007_delete_carro"),
    ]

    operations = [
        migrations.AddField(
            model_name="proprietario",
            name="cor",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Amarelo"), (2, "Azul"), (3, "Cinza")],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="proprietario",
            name="modelo",
            field=models.IntegerField(
                blank=True,
                choices=[("H", "hatch"), ("S", "Sedan"), ("C", "Conversível")],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="proprietario",
            name="nome_carro",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
